config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "about", to: "about#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registerations#new"
  post "sign_up", to: "registerations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "auth/twitter/callback", to: "omniauth_callbacks#twitter"

  resources :twitter_accounts
  resources :tweets

  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  has_many :tweets
  validates :username, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :twitter_accounts
    has_many :tweets
    has_secure_password
    validates :email, presence: true, uniqueness: true, format: {with: /\A\S+@.+\.\S+\z/, message: "Must be a valid email address"}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    
    def index
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # protect_from_forgery with: :null_session
    before_action :set_current_user
 
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
       
    end
end 

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
    def twitter
        Rails.logger.info auth

       twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
       twitter_account.update(
           name: auth.info.name,
           username: auth.info.nickname,
           image: auth.info.image,
           token: auth.credentials.token,
           secret: auth.credentials.secret,
       )

       redirect_to twitter_accounts_path, notice: "Successfully conncted your Twitter account!"
    end

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            #send email
            PasswordMailer.with(user: @user).reset.deliver_later
        end
        redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password."
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token has expired, please try again."
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        print @user
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your password was reset succesffully. Please sign in"
            puts "UPDATED"
        else
            puts "NOT UPDATED"
            render :edit
        end
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token has expired, please try again."
    end 
    
    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password Updated"

        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registerations_controller.rb
class RegisterationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully created account"
            # render json: @user
        else
            render :new
        end
    end

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Logged in successfully!"
            # render json: @user
        else
            flash[:alert] = "Invalid email or password"
            render :new
            # render json: @user
        end
    end 

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :require_user_logged_in!

    def index
        @tweets = Current.user.tweets
    end

    def new
        @tweet = Tweet.new
    end

end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_twitter_account, only: [:destroy]

    def index
        @twitter_accounts = Current.user.twitter_accounts
    end

    def destroy
        @twitter_account.destroy
        redirect_to twitter_accounts_path, notice: "Successfully disconnected @#{@twitter_account.username}"
    end

    def set_twitter_account
        @twitter_account = Current.user.twitter_accounts.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>

  <div class="container">
    <%= render partial: "shared/flash" %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1> Welcome to Scheduled Tweets</h1>
</div>  

<%= button_to "Connect Twitter", "/auth/twitter", method: :post, class: "btn btn-primary" %>

app/views/password_resets/edit.html.erb
<h1> Reset your passowrd? </h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>

     <% if form.object.errors.any? %>
    <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
    <% end %>
    </div>
    <% end %>

    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
    </div>

     <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h1> Forgot your passowrd? </h1>

<%= form_with url: password_reset_path do |form| %>
    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", placeholder: "steve@apple.com" %>
    </div>

    <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/registerations/new.html.erb
<h1>Sign up</h1>

<%= form_with model: @user, url: sign_up_path do |form| %>
    <% if form.object.errors.any? %>
    <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
    <% end %>
    </div>
    <% end %>
    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", placeholder: "steve@apple.com" %>
    </div>
    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
    </div>

    <div class="mb-3">
    <%= form.submit "Sign Up", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert"> 
    <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert"> 
    <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Scheduled Tweets", root_path, class:"nav-link" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "Tweets", tweets_path, class:"nav-link" %>
        </li>
          <li class="nav-item">
        <%= link_to "Twitter Accounts", twitter_accounts_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "About", about_path, class:"nav-link" %>
        </li>
      </ul>
      
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if Current.user %>
        <li class="nav-item">
          <%= link_to Current.user.email, edit_password_path, class:"nav-link" %>
          </li>
        <li class="nav-item">
          <%= button_to "Logout", logout_path, method: :delete, class:"nav-link" %>
          </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", sign_up_path, class:"nav-link" %>
          </li>
        <li class="nav-item">
          <%= link_to "Login", sign_in_path, class:"nav-link" %>
          </li>
      <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center">
    <h1> Tweets </h1>

    <% if Current.user.twitter_accounts.any? %>
    <%= link_to "Schedule a Tweet", new_tweet_path, class: "btn btn-primary"%>
    <% end %>
</div>


<% if Current.user.twitter_accounts.none? %>
<%= link_to "Connect your Twitter Account", "/auth/twitter", method: :post, class: "btn btn-primary" %>
<% end %>

app/views/tweets/new.html.erb
<h1> Schedule A Tweet </h1>

<%= form_with model: @tweet do |form| %>
<div class="mb-3">
    <%= form.label :twitter_account_id%>
    <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, {class: "form-control"} %>
    <%= link_to "Connect your Twitter Account", "/auth/twitter", method: :post %>
</div> 

<div class="mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
</div>

<div class="mb-3">
    <%= form.label :publish_at %>
    <div class="form-control">
        <%= form.datetime_select :publish_at %>
    </div>
</div>

<%= form.button "Schedule", class: "button btn-primary" %>
<% end %>

app/views/twitter_accounts/index.html.erb
<div class="d-flex align-items-center justify-content-between">
    <h1>Twitter Accounts </h1>
    <%= link_to "Connect a Twitter account", "/auth/twitter", method: :post, class: "btn btn-primary" %>
</div>

<% @twitter_accounts.each do |twitter_account| %>
    <div class="d-flex align-items-center mb-4">
        <div class="me-4">
            <%= image_tag twitter_account.image, class: "rounded_circle" %>
            <%= link_to "@#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}", target: :_blank %>
        </div>

        <%= button_to "Disconnect", twitter_account, method: :delete, data: {confirm: "Are you sure you want to unlink this account?"} %>
    </div>
<%end %>